### ISSUE TITLE
显示消息 正在发送中。。

### ISSUE THREAD

**Issue by TonyStonem** [WANZIzZ/WeChatRobot#2]
我使用的微信是7.0.7版本，clz_aw是com.tencent.mm.model.az，方法clz_p是ZS了，其他不变 调用之后一直显示正在发送中状态。。这是为什么啊

**Comment by WANZIzZ** [comment]
我测试了一下，是正常的。

**Comment by TonyStonem** [comment]
大佬 我今天试了一下 也是正常的，好奇怪 昨天就是不行 不过ok了 谢谢啦
