### ISSUE TITLE
如何生成分析文件?

### ISSUE THREAD

**Issue by DoveBarnett** [WANZIzZ/WeChatRobot#3]
我这边选择生成文件的按钮是灰色的，你那边是怎么看到微信进程的？

**Comment by WANZIzZ** [comment]
你切换一下 USB连接选项 试试

**Comment by DoveBarnett** [comment]
切换到哪个？传输文件？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"乘风"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 上午10:30
收件人:&nbsp;"WANZIzZ/WeChatRobot"<WeChatRobot@noreply.github.com&gt;;
抄送:&nbsp;"暖冬"<2291493676@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WANZIzZ/WeChatRobot] 如何生成分析文件? (#3)




你切换一下 USB连接选项 试试

**Comment by WANZIzZ** [comment]
充电和传输文件都切换一下试试，好像每切换一次，那个显示进程的列表就会刷新。

**Comment by DoveBarnett** [comment]
还是不行啊，是需要root权限吗？还是跟系统版本有关？之前好像听说，安卓5还是6之后都看不了其他应用进程了。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"乘风"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 中午11:31
收件人:&nbsp;"WANZIzZ/WeChatRobot"<WeChatRobot@noreply.github.com&gt;;
抄送:&nbsp;"暖冬"<2291493676@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WANZIzZ/WeChatRobot] 如何生成分析文件? (#3)




充电和传输文件都切换一下试试，好像每切换一次，那个显示进程的列表就会刷新。

**Comment by WANZIzZ** [comment]
跟系统版本应该没有关系，我用Android7.1.2和Android9.0都试过，可以的，我手机是Root过的

**Comment by DoveBarnett** [comment]
那应该是root过的才可以吧，谢谢啦！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"乘风"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 下午5:18
收件人:&nbsp;"WANZIzZ/WeChatRobot"<WeChatRobot@noreply.github.com&gt;;
抄送:&nbsp;"暖冬"<2291493676@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WANZIzZ/WeChatRobot] 如何生成分析文件? (#3)




跟系统版本应该没有关系，我用Android7.1.2和Android9.0都试过，可以的，我手机是Root过的

**Comment by WANZIzZ** [comment]
没事，你root完试试看
