### ISSUE TITLE
请问主动发消息怎么做呢？

### ISSUE THREAD

**Issue by lexluthors** [WANZIzZ/WeChatRobot#4]
请问主动发消息怎么做呢？就是指定某个联系人或者群发送消息。不是自动的，是手动点击按钮指定发送。

**Comment by WANZIzZ** [comment]
你的意思我没看懂，不过主动发消息的话，分两种，一种是用无障碍服务做的，就是模拟点击这样，一种是用Xposed来做，调用微信自己的函数来实现。

**Comment by lexluthors** [comment]
@WANZIzZ 作者你好，调用微信自己的函数需要传递参数，我把你那个自动发消息的方法抽取出来了，但是应用直接闪退了。
 val clz_h = XposedHelpers.findClass("com.tencent.mm.modelmulti.h", lpparam.classLoader)
                    val message = XposedHelpers.newInstance(clz_h, talker, content, 1)
                    val clz_aw = XposedHelpers.findClass("com.tencent.mm.model.aw", lpparam.classLoader)
                    val clz_p = XposedHelpers.callStaticMethod(clz_aw, "Vs")
                    XposedHelpers.callMethod(clz_p,"a",message,0)
就是这个，需要传递classloader，这个classloader从哪获取呢？我是保存了一个全局的。但是还是报错。

**Comment by WANZIzZ** [comment]
classloader 是从 handleLoadPackage 函数传入的 XC_LoadPackage.LoadPackageParam 里面获取的

**Comment by lexluthors** [comment]
@WANZIzZ 你能否在这个项目中添加一个示例呢？就是写个按钮，点击就指定一个联系人发送一个消息。我用这个方法试了没有效果呢。版本和你的是一致的。

**Comment by WANZIzZ** [comment]
我给你举个例子，比如你把发送消息封装成了一个方法
~~~
fun sendMsg(classloader:ClassLoader,username:String,msg:String){
   ...
}
~~~
然后你调用的时候，可以这样写
~~~
fun handleLoadPackage(lpparam: LoadPackageParam) {
   if (lpparam.packageName=="微信包名") {
       sendMsg(lpparam.classloader,"","")
   }
}
~~~

**Comment by lexluthors** [comment]
@WANZIzZ 你这个调用的地方，是必须在handleLoadPackage中调用吗？但是，我是在activity中调用的，没有handleLoadPackage这个回调函数怎么办呢？

**Comment by WANZIzZ** [comment]
这个就需要跨进程通讯了。

**Comment by lexluthors** [comment]
@WANZIzZ 额，感觉好麻烦。这个插件是开机就加载了是吧。和打开的插件APP不是同一个进程是吧？

**Comment by WANZIzZ** [comment]
是的，不是同一个进程。

**Comment by lexluthors** [comment]
@WANZIzZ 好的，谢谢啦
